name: "Deploy CloudFormation Stack"
on: 
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy infrastructure with CloudFormation
      id: infrastructure-stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: "test-stack-from-git"  
        template: cloudformation-templates/infrastructure.yml
        no-fail-on-empty-changeset: "1"
